# Generated by Django 4.2.5 on 2023-09-24 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='authority',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='citizenship',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_expiry',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_issue',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='ethnicity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='place_of_birth',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.notification'),
        ),
    ]
